version: '2'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry-service

  gateway:
    build: gateway-service

  auth-service:
    build: auth-service
    ports:
      - 5000:5000

  monitoring:
    build: monitoring-service